### ISSUE TITLE
Make sure that landing-page information is present in MMD and that it is a valid url

### ISSUE THREAD

**Issue by johtoblan** [metno/discovery-metadata-catalog-ingestor#126]

**Comment by charlienegri** [comment]
is something like adding a check for `landing_page`in full_check (https://github.com/metno/discovery-metadata-catalog-ingestor/blob/main/dmci/tools/check_mmd.py#L281) enough? and is `landing_page` the name of the attribute? I cannot find it in either CF or ACDD so the name is probably something else..

**Comment by mortenwh** [comment]
> is something like adding a check for the landing page in full_check (https://github.com/metno/discovery-metadata-catalog-ingestor/blob/main/dmci/tools/check_mmd.py#L281) enough? 

Yes, I think so. Landing page is an MMD "related_information" field with `type="Dataset landing page"`. It is not obvious that it should be there, as it is not required, so I'm not sure if we can use the `mmd_strict.xsd` to check this. Probably better to add some python lines.

> and what is the name of the attribute? 

Example:
```
<related_information>
    <type>Dataset landing page</type>
    <resource>https://data.met.no/dataset/<uuid></resource>
</related_information>
```
The url should be pointing to our production server, or maybe be dynamically created. The latter is maybe best, but then we have to handle this in dmci itself. This could be done based on the environment (dev, staging or production) and the dataset uuid. In this case, we need to add the field to the MMD string before distribution to file, pycsw and solr.

> I cannot find anything like `landing_page` or similar in either CF or ACDD so the name is probably something else.. and also it must not be a resource otherwise there would be no need to check the url, right?

Not sure what you mean, but I think we can only check the url pattern. Anyway, the check is maybe not that important if the landing page field is added by dmci itself.

**Comment by mortenwh** [comment]
> * if I understand correctly by seeing issue "Add landing page information when creating mmd#225", the landing page info would be created elsewhere (edit: this is https://github.com/metno/py-mmd-tools/issues/225)

Yes, it could be done in py-mmd-tools but when I think about it, it may be better in dmci since it is strongly connected to the data site/system which is "known" in the dmci service. @johtoblan - what do you think? In that case, we can close https://github.com/metno/py-mmd-tools/issues/225.

>     * as for the url check what  I mean is that the code currently already checks for all the urls that are in the "resources" category  https://github.com/metno/discovery-metadata-catalog-ingestor/blob/main/dmci/tools/check_mmd.py#L303

Ok, then that may be enough.

**Comment by mortenwh** [comment]
Discussed in review meeting now. We add data.met.no in the MMD files. This can be changed in dmci to adjust for dev and staging envs.

**Comment by mortenwh** [comment]
Update: the landing page should be set by dmci, since this is the entry point for the data management service. See https://github.com/metno/py-mmd-tools/issues/225

**Comment by charlienegri** [comment]
should this happen only for `/v1/create` or `/v1/insert` kinda events or also for `/v1/validate`?
because if the former then it could be part of the `_insert_update_method_post` function https://github.com/metno/discovery-metadata-catalog-ingestor/blob/main/dmci/api/app.py#L113 and instead if the latter then it must be probably its own function which will be called by `_validate_method_post` too and not just `_insert_update_method_post`

**Comment by johtoblan** [comment]
So you use verify, get a Everything is ok, and then it fails on update/insert?

**Comment by charlienegri** [comment]
mmh I do not fully understand how `_validate_method_post` and `post_validate()` work in context but for now I would write a function called something add_landing_page that would be called after checks like `worker.validate(data)` and then takes the byte string `data` and the uuid (or extracts is if we do not want modify other places so that it's passed out) and adds the needed chars via regex.. (easy to do it just before the last `\n</mmd:mmd>\n` if there is no `related_information`, not sure how to handle the case where the field is already present in the xml file..)

**Comment by mortenwh** [comment]
> So you use validate, get a Everything is ok, and then it fails on update/insert?

Why should it fail on update/insert?

**Comment by mortenwh** [comment]
> mmh I do not fully understand how `_validate_method_post` and `post_validate()` work in the context of the full chain, but for now I could write a function called something add_landing_page that would be called after checks like `worker.validate(data)` and then takes the byte string `data` and the uuid (or extracts is if we do not want modify other places so that it's passed out) and adds the needed chars via regex.. (easy to do it just before the last `\n</mmd:mmd>\n` 

It needs to be in the right place in the MMD because of how the xsd is defined. Check `mmd_strict.xsd`to find the right place.

> if there is no `related_information`, not sure how to handle the case where the field is already present in the xml file..)... 

I think you'll need to replace it if it's already there, or check and replace if it is incorrect.

**Comment by johtoblan** [comment]
> > So you use validate, get a Everything is ok, and then it fails on update/insert?
> 
> Why should it fail on update/insert?

If we add validation to the update/insert that is not present in validate

**Comment by mortenwh** [comment]
> > > So you use validate, get a Everything is ok, and then it fails on update/insert?
> > 
> > 
> > Why should it fail on update/insert?
> 
> If we add validation to the update/insert that is not present in validate

But that shouldn't be a problem as long as we know the internal functionality is correct? We can make sure it works using unit tests..?

**Comment by charlienegri** [comment]
> mmd_strict.xsd

you mean `/tests/files/mmd/mmd.xsd`?
how can it be placed in the right order agnostically of what other fields are present? like, we do not expect a predictable number of fields the mmd files, beyond the mandatory ones.. or am I missing something?

**Comment by johtoblan** [comment]
> > mmd_strict.xsd
> 
> you mean `/tests/files/mmd/mmd.xsd`? how can it be placed in the right order agnostically of what other fields are present? like, we do not expect a predictable number of fields the mmd files, beyond the mandatory ones.. or am I missing something? like for example, where would it be placed in an example like `tests/files/api/passing.xml`?

https://github.com/metno/mmd/blob/master/xsd/mmd_strict.xsd

**Comment by magnarem** [comment]
The host url for the landingpages should also change with respect to environments.

Now new precessed mmd-files sendt to mmd-xml-dev, still have https://data.met.no/dataset/<uuid>
should be https://data-test.met.no/dataset/<uuid> for dev environment and https://data-staging.met.no/dataset/<uuid> for staging environment

**Comment by charlienegri** [comment]
yeah, that will be read from the config

**Comment by mortenwh** [comment]
@magnarem - should we also change the `metadata_identifier` from  `no.met:<uuid>` to `no.met.dev:<uuid>` and `no.met.staging:<uuid>` for the dev and staging envs as part of this?

**Comment by charlienegri** [comment]
as far as I understand the order in a xsd template matters only inside of the `xs:sequence` indicator blocks, so if there is no `related_information` in data already, adding it before the last `</mmd:mmd>` should be fine right? otherwise I can't think of an easy way of doing it that would hold for whatever possible valid xml file/data string

**Comment by charlienegri** [comment]
sure @mortenwh, fine by me, the idea of having something `_string` is that I though we woud preserve the existing `namespace` and just append `.dev`/`.staging` or nothing, but I guess there's no way there can be anything else, or we want to have anything else than `no.met` ?? if that's the case then having the whole `namespace` in the conf instead of just `environment_string` is ok I guess

**Comment by charlienegri** [comment]
but anyway I'll change from `web_catalog` to `overrides` in the PR attached to this issue, so that it's already there for issue #147

**Comment by mortenwh** [comment]
Sounds good! In case others want to use dmci, I guess the full namespace (e.g., `no.met.staging`) is best.
