### ISSUE TITLE
Create an easy workflow for checking, correcting and retrying ingestion of rejected files

### ISSUE THREAD

**Issue by mortenwh** [metno/discovery-metadata-catalog-ingestor#160]
Currently, rejected files are stored in a folder but we need to have system for following up when files are rejected.

For example:
* How to get the files out and do debugging?
* How to remove files from the rejected folders?
* How to follow up rejected files? Should we check manually on a regular basis, or should we have some automatic reporting?

**Comment by magnarem** [comment]
I see a couple of solution for this.

Maybe the simplest solution will be to define a kubernets cronjob that will watch the /rejected folder on a regular basis.
If there are files in the rejected folder, the cronjob can archive those and email them to a recivier, and then clean the /rejected folder.

Another solution is to make another container dmci-admin. That can only be accessed with some form of authentication.
With this solution we  have a means to inspect the xml and txt files in the rejected folder, with something similar apache directory listing. And implement a button for downloading and cleaning the rejected folder.
In such a container, it would also be possible to add admin functions for cleaning the pycsw-database and the solr index, for prepearing the catalog-rebuilder. This will also be a workaround for cleaning the staging and prod, since we will get the credentials inside the dmci-admin container for do the cleaning of the database and index.

**Comment by magnarem** [comment]
If we go for a solution making a dmci-admin container, this python package/module, have a lot of features that we can use:

https://pypi.org/project/browsepy/

* **Simple**, like Python's SimpleHTTPServer or Apache's Directory Listing.
* **Downloadable directories**, streaming directory tarballs on the fly.
* **Optional remove** for files under given path.
* **Optional upload** for directories under given path.
* **Player** audio player plugin is provided (without transcoding).* 

The latest version are a bit old, but in github there are som PRs with updates that we can use (zip streaming support, and python 3.10 support)

**Comment by magnarem** [comment]
I started a version of the catalog-rebuilder which will run as a flask app and a deployment instead of a kubernets-job, which makes all kid of problems.

Check rebuilder_admin.py for referenece (scaffolding for a flask app). This will handle delete and download of rejected files.

https://github.com/metno/catalog-rebuilder/blob/flask_app_version/catalog_admin.py

**Comment by shamlymajeed** [comment]
https://gitlab.met.no/s-enda/container-periodic-git-pusher/-/merge_requests/5
https://gitlab.met.no/tjenester/s-enda/-/merge_requests/2776
Can close this issue if above PRs are merged.

**Comment by shamlymajeed** [comment]
https://gitlab.met.no/s-enda/container-periodic-git-pusher/-/merge_requests/5
https://gitlab.met.no/tjenester/s-enda/-/merge_requests/2776
Can close this issue if above PRs are merged.

**Comment by johtoblan** [comment]
Added this to dev now, to see how it works.

**Comment by shamlymajeed** [comment]
https://gitlab.met.no/s-enda/container-periodic-git-pusher/-/merge_requests/6
https://gitlab.met.no/tjenester/s-enda/-/merge_requests/2781
